### ISSUE TITLE
Error: 12.1.2 Causes node issue when implementing Helia

### ISSUE THREAD

**Issue by TheGreatAlgo** [multiformats/js-mafmt#154]
`error @multiformats/mafmt@12.1.2: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.16.0"`
This latest `12.1.2` change causes issues with node version `16.16`.

This is due to dependencies here

`@libp2p/bootstrap@^6.0.3`
`@libp2p/websockets@^5.0.10`
`libp2p@^0.44.0`

They all have `"@multiformats/mafmt" "^12.0.0"` because of this they try to install `12.1.2` which breaks with older node version and I am unable to use a prior version due to this setting

![image](https://github.com/multiformats/js-mafmt/assets/37487508/a59fce20-f377-46bc-a37a-656c7e8e2f3c)

**Comment by achingbrain** [comment]
Can you update to LTS node?  We only run CI on LTS so there's no guarantee anything will work on maintenance or other legacy versions.

**Comment by Faolain** [comment]
Hey @achingbrain we have some other dependencies that unfortunately only work with node 16 atm. Would it be possible to instead bump the major version for this package with this node upgrade instead, for example instead of 12.1.2 a change to 13? (and the corresponding libraries @libp2p/bootstrap, @libp2p/websockets, libp2p can also update their package set)This way it would prevent rolling breaking changes across other apps that could depend on a specific node version. 

Since this change is a breaking change it seems based on semantic versioning this should be a major change (aka 13 instead of a patch fix based on https://docs.npmjs.com/about-semantic-versioning) 

<img width="852" alt="Screenshot 2023-05-16 at 2 23 53 PM" src="https://github.com/multiformats/js-mafmt/assets/9613083/df044d19-3347-4eaa-bcaa-5f416f15aa3c">

**Comment by BigLep** [comment]
@achingbrain: (inexperienced here on the tooling) will https://github.com/ipfs/aegir/issues/1276 address this?

**Comment by achingbrain** [comment]
#155 will fix it, https://github.com/ipfs/aegir/issues/1276 / https://github.com/ipfs/aegir/pull/1277 will prevent it from recurring in future.

**Comment by achingbrain** [comment]
> we have some other dependencies that unfortunately only work with node 16 atm

@Faolain out of interest what are they?  Node 16 is EOL in September so it'd be good to know what people are still using.
